### ISSUE TITLE
Feature request: background color

### ISSUE THREAD

**Issue by pnrao** [AlfredoRamos/urbanlifestyle-sddm-theme#1]
As far as usability is concerned, this theme is the best I have seen. However the background is somewhat on the NSFW side. I have changed the background to use a different picture now, but the picture is predominantly black, and does not conform to my monitor's aspect ratio. As a result, I see two white vertical bars on each side of the image.

Can you please provide a feature to set a default background color via theme.conf?

**Comment by AlfredoRamos** [comment]
I just did some changes, can you please test it before I release a new version?

**Comment by pnrao** [comment]
Sorry about the late reply. I was out of town. The new changes are perfect. Thank you.
